[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
" denite時に使用するキーマップ
" ESCキーでdeniteを終了
call denite#custom#map('insert', '<esc>', '<denite:enter_mode:normal>', 'noremap')
call denite#custom#map('normal', '<esc>', '<denite:quit>', 'noremap')
" C-N,C-Pで上下移動
call denite#custom#map('insert', '<C-n>', '<denite:move_to_next_line>', 'noremap')
call denite#custom#map('insert', '<C-p>', '<denite:move_to_previous_line>', 'noremap')
" C-J,C-Kでsplitで開く
call denite#custom#map('insert', '<C-j>', '<denite:do_action:split>', 'noremap')
call denite#custom#map('insert', '<C-k>', '<denite:do_action:vsplit>', 'noremap')
" C-Cでカレントディレクトリ変更
call denite#custom#map('insert', '<C-o>', '<denite:do_action:cd>', 'noremap')
call denite#custom#map('normal', '<C-o>', '<denite:do_action:cd>', 'noremap')

" 以下はdenite起動時に使用するキーマップ
" バッファ一覧
noremap <C-P> :Denite buffer<CR>
" ファイル一覧
noremap <C-N> :Denite -buffer-name=file file<CR>
" 最近使ったファイルの一覧
noremap <C-Z> :Denite file_mru<CR>
" カレントディレクトリ
noremap <C-C> :Denite file_rec<CR>
" バッファ一覧
nnoremap sB :<C-u>Denite buffer -buffer-name=file<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

